# SITE CONFIGURATION
baseurl: "/Threat-Intel-Reports"
url: "https://pixelatedcontinuum.github.io"

# THEME-SPECIFIC CONFIGURATION
title: The Hunter's Ledger
description: "Threat Intelligence Reports and Hunting Resources"

favicon: "/assets/images/favicon.ico"

# Header and footer text
header_text: The Hunter's Ledger
header_feature_image: /assets/images/header.png
header_feature_image_responsive: true
footer_text: Threat Intel by The Hunterâ€™s Ledger

# Blog / Post settings
excerpt: true
post_navigation: true
color_image: /assets/images/lineart.png
color_theme: dark

# Features
katex: true
mermaid: default
google_analytics:
cookie_consent: false

# PAGINATION
paginate: 5
paginate_path: "/blog/page:num"

# BUILD SETTINGS
sass:
  style: compressed
  quiet_deps: true

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed

exclude:
  - ".jekyll-cache"
  - ".jekyll-metadata"
  - ".idea"
  - "vendor/*"
  - "assets/node_modules/*"
  - ".github/*"

# Theme activation
remote_theme: sylhare/Type-on-Strap