title: The Hunter's Ledger
description: Threat Intelligence Reports and Hunting Resources
url: "https://pixelatedcontinuum.github.io"
baseurl: "/Threat-Intel-Reports"

theme: null

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
