title: The Hunter's Ledger
description: Threat Intelligence Reports and Hunting Resources

url: "https://pixelatedcontinuum.github.io"
baseurl: "/Threat-Intel-Reports"

remote_theme: sylhare/Type-on-Strap
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-paginate

color_theme: dark   # force dark mode (use 'auto' for toggle)
logo: "/assets/images/logo.png"

# Optional metadata
markdown: kramdown
highlighter: rouge
permalink: pretty

paginate: 5
paginate_path: "blog/page:num"
